
name: Odoo Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-odoo:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up environment variables
      run: |
        echo "ODOO_PATH=/home/irfan-706/workspace/odoo_local/odoo" >> $GITHUB_ENV
        echo "ODOO_CONFIG=/home/irfan-706/workspace/odoo_local/odoo/config/odoo18.conf" >> $GITHUB_ENV
        echo "VENV_PATH=/home/irfan-706/workspace/odoo_local/.venv" >> $GITHUB_ENV
        
    - name: Activate virtual environment and install dependencies
      run: |
        source $VENV_PATH/bin/activate
        pip install --upgrade pip
        # Install any additional requirements if needed
        # pip install -r requirements.txt
        
    - name: Run Odoo database update (if needed)
      run: |
        source $VENV_PATH/bin/activate
        python $ODOO_PATH/odoo-bin -c $ODOO_CONFIG -d ${{ secrets.ODOO_DB_NAME }} -u all --stop-after-init --no-http
      continue-on-error: true
      
    - name: Run Odoo tests
      run: |
        source $VENV_PATH/bin/activate
        python $ODOO_PATH/odoo-bin -c $ODOO_CONFIG -d ${{ secrets.ODOO_DB_TEST }} --test-enable --stop-after-init --no-http
      continue-on-error: true
      
    - name: Start Odoo server (health check)
      run: |
        source $VENV_PATH/bin/activate
        timeout 30s python $ODOO_PATH/odoo-bin -c $ODOO_CONFIG --no-database-list || true
        
    - name: Cleanup
      run: |
        # Kill any remaining Odoo processes
        pkill -f odoo-bin || true
