name: Test Local VM Odoo

on:
  push:
    branches: [ main ]

jobs:
  test-odoo:
    runs-on: [self-hosted, linux]
    steps:
      - name: Check Odoo status
        run: |
          sudo systemctl status odoo || true

      - name: Test HTTP endpoint
        run: |
          curl -I http://localhost:8069 || true

      - name: Activate virtual environment and run tests
        run: |
          source /home/irfan-706/workspace/odoo_local/.venv/bin/activate
          python3 /home/irfan-706/workspace/odoo_local/odoo/odoo-bin \
              -c /home/irfan-706/workspace/odoo_local/odoo/config/odoo.conf \
              -d odoo_db_test --xmlrpc-port=8071 \
              -i obase,website,auth_oauth,hr,hr_contract,hr_attendance,hr_holidays,portal,mail,hr_timesheet,project,sale_timesheet,odoo_portal

      - name: Delete test database
        continue-on-error: true
        run: |
          dropdb -h localhost -U postgres odoo_db_test || true
