name: Test Local VM Odoo

on:
  push:
    branches: [ main ]

jobs:
  test-odoo:
    runs-on: [self-hosted, linux]
    steps:
      - name: Check Odoo status
        run: |
          sudo systemctl status odoo || true

      - name: Test HTTP endpoint
        run: |
          curl -I http://localhost:8069 || true

      - name: Activate virtual environment
        run: |
          source /home/odoo/src/venv/bin/activate
          # Update modules in running Odoo
          /home/odoo/src/venv/bin/python3 /home/odoo/src/odoo/odoo-bin \
              -c /home/odoo/src/odoo/config/odoo.conf \
              -d odoo_db_test --xmlrpc-port=8071 \
              -i obase,website,auth_oauth,hr,hr_contract,hr_attendance,hr_holidays,portal,mail,hr_timesheet,project,sale_timesheet,odoo_portal \
              --test-enable \
              --stop-after-init
           

          # # Restart Odoo service
          # sudo systemctl restart odoo
            
