# Create workflow directory in custom-modules
sudo su - odoo
cd ~/src/custom-modules
mkdir -p .github/workflows

# Create workflow file
cat > .github/workflows/deploy.yml << 'EOF'
name: Deploy Odoo Custom Modules

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, odoo, local]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Pull latest changes
      run: |
        cd /home/odoo/src/custom-modules
        git pull origin main
        
    - name: Restart Odoo service
      run: |
        sudo systemctl restart odoo
        
    - name: Check service status
      run: |
        sleep 10
        sudo systemctl is-active --quiet odoo && echo "Odoo service is running" || echo "Odoo service failed to start"
EOF
