name: Deploy Custom Modules

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Pull latest custom modules
      run: |
        cd /home/irfan-706/workspace/odoo_local/custom_addons/dsinv-odoo
        git pull origin main
        
    - name: Rebuild Odoo
      run: |
        sudo systemctl restart odoo-rebuild
        
    - name: Wait for rebuild to complete
      run: |
        # Wait for the service to complete
        sleep 30
        
        # Check if rebuild was successful
        if sudo systemctl is-active --quiet odoo; then
          echo "✅ Odoo rebuilt and started successfully!"
        else
          echo "❌ Odoo rebuild failed"
          sudo journalctl -u odoo-rebuild --no-pager -n 20
          exit 1
        fi
